services:
  llvm14:
    build: llvm14/
    volumes:
      - ./llvm14:/workspace
    command: bash -c "mkdir -p build && cd build && cmake .. && make && tail -f /dev/null"

  llvm20:
    build: llvm20/
    volumes:
      - ./llvm20:/workspace
    command: bash -c "mkdir -p build && cd build && cmake .. && make && tail -f /dev/null"
    
